### ISSUE TITLE
Missing version number

### ISSUE THREAD

**Issue by msailes** [hkupty/maple#120]
When using Penna the initialization message doesn't include the pennaVersion. 

```{"logger":"penna.api.audit.Logger","level":"INFO","message":"Penna initialized successfully","pennaVersion":"null"}```

Expected: To show the Penna version

Actual: Currently showing null

**Comment by hkupty** [comment]
As I stated in the PR, I'll set up some integration test suite. As a reminder, I'll keep this issue open until I can _prove_ it was fixed by those tests :)

**Comment by hkupty** [comment]
I finally got some time to push through and finished the integration tests. Build is now fixed to ensure the projects get the version and we have a test that verifies it at every PR run. Thank you so much for your help and sorry for leaving you hanging for so long 😅
